version: '3.1'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: pass_db
      POSTGRES_DB: vehicles_finder_db
    ports:
      - 5434:5432
